// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtixIy-FLnc2JCJG5smwJIhsSpBjRC9w0',
    appId: '1:404732078035:web:f556d772ae0b29034ff126',
    messagingSenderId: '404732078035',
    projectId: 'voleyapp-77661',
    authDomain: 'voleyapp-77661.firebaseapp.com',
    storageBucket: 'voleyapp-77661.firebasestorage.app',
    measurementId: 'G-H537ZKQN7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDYQQTMejfxvujngUhBHu2CGh3Wmkc0E4',
    appId: '1:404732078035:android:5900663de485ea164ff126',
    messagingSenderId: '404732078035',
    projectId: 'voleyapp-77661',
    storageBucket: 'voleyapp-77661.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqe0BOnv6twus1QZ-85V1l7eACQfuYlo8',
    appId: '1:404732078035:ios:dfff5423e35a48df4ff126',
    messagingSenderId: '404732078035',
    projectId: 'voleyapp-77661',
    storageBucket: 'voleyapp-77661.firebasestorage.app',
    iosBundleId: 'com.example.voleyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqe0BOnv6twus1QZ-85V1l7eACQfuYlo8',
    appId: '1:404732078035:ios:dfff5423e35a48df4ff126',
    messagingSenderId: '404732078035',
    projectId: 'voleyapp-77661',
    storageBucket: 'voleyapp-77661.firebasestorage.app',
    iosBundleId: 'com.example.voleyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtixIy-FLnc2JCJG5smwJIhsSpBjRC9w0',
    appId: '1:404732078035:web:63e4d3ac7425a4344ff126',
    messagingSenderId: '404732078035',
    projectId: 'voleyapp-77661',
    authDomain: 'voleyapp-77661.firebaseapp.com',
    storageBucket: 'voleyapp-77661.firebasestorage.app',
    measurementId: 'G-8TDHFCP9F6',
  );
}
