// lib/seeders/gym_exercise_seeder.dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:voley_app/src/catalogos/enums.dart';
import 'package:voley_app/src/models/bd/exercise.dart';

/// LISTA PRINCIPAL: 50 ejercicios de fuerza / hipertrofia / calistenia
final List<Exercise> gymExercises = [

  // =========================
  // 1) PIERNA - FUERZA / HIPERTROFIA
  // =========================

  Exercise(
    id: 'ex_back_squat_barbell',
    slug: 'back_squat_barbell',
    name: 'Sentadilla Trasera con Barra',
    description:
        'Sentadilla clásica con barra en la espalda. Base de fuerza de tren inferior (cuádriceps, glúteos, core).',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.glutes, MuscleGroupId.core, MuscleGroupId.erectors],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.jump, VolleyballTransferId.landing],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.preSeason, TrainingPhaseId.inSeason],
    equipmentIds: [EquipmentId.barra, EquipmentId.discos, EquipmentId.banco],
    contraindicationIds: [ContraindicationId.rodilla, ContraindicationId.lumbar],
  ),

  Exercise(
    id: 'ex_front_squat_barbell',
    slug: 'front_squat_barbell',
    name: 'Sentadilla Frontal con Barra',
    description:
        'Sentadilla con la barra en rack frontal. Mayor demanda de core y cuádriceps, excelente para atletas.',
    videoUrl: '',
    levelId: LevelId.advanced,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.glutes, MuscleGroupId.core],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.jump, VolleyballTransferId.landing],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.preSeason],
    equipmentIds: [EquipmentId.barra, EquipmentId.discos],
    contraindicationIds: [ContraindicationId.rodilla, ContraindicationId.lumbar],
  ),

  Exercise(
    id: 'ex_goblet_squat',
    slug: 'goblet_squat',
    name: 'Sentadilla Goblet',
    description:
        'Sentadilla sujetando mancuerna o kettlebell frente al pecho. Ideal para aprender técnica y para hipertrofia.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.glutes, MuscleGroupId.core],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.jump],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.mancuernas, EquipmentId.kettlebell],
    contraindicationIds: [ContraindicationId.rodilla],
  ),

  Exercise(
    id: 'ex_bulgarian_split_squat_db',
    slug: 'bulgarian_split_squat_db',
    name: 'Sentadilla Búlgara con Mancuernas',
    description:
        'Sentadilla unilateral con el pie trasero elevado en banco. Gran estímulo de cuádriceps y glúteos.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.lunge,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.glutes, MuscleGroupId.core],
    qualityIds: [QualityId.strength, QualityId.stability],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.jump, VolleyballTransferId.approach],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.preSeason, TrainingPhaseId.offSeason],
    equipmentIds: [EquipmentId.mancuernas, EquipmentId.banco],
    contraindicationIds: [ContraindicationId.rodilla],
  ),

  Exercise(
    id: 'ex_walking_lunge_db',
    slug: 'walking_lunge_db',
    name: 'Zancadas Caminando con Mancuernas',
    description:
        'Lunges en desplazamiento con carga. Trabaja fuerza unilateral, estabilidad y control del tronco.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.lunge,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.glutes, MuscleGroupId.hamstrings, MuscleGroupId.core],
    qualityIds: [QualityId.strength, QualityId.stability],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.approach, VolleyballTransferId.defenseShuffle],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.mancuernas],
    contraindicationIds: [ContraindicationId.rodilla],
  ),

  Exercise(
    id: 'ex_barbell_rdl',
    slug: 'barbell_rdl',
    name: 'Peso Muerto Rumano con Barra',
    description:
        'Bisagra de cadera con ligera flexión de rodilla. Enfocado en isquiosurales y glúteos, clave para salto.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.hinge,
    muscleGroupIds: [MuscleGroupId.hamstrings, MuscleGroupId.glutes, MuscleGroupId.erectors],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.jump, VolleyballTransferId.landing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.barra, EquipmentId.discos],
    contraindicationIds: [ContraindicationId.lumbar],
  ),

  Exercise(
    id: 'ex_barbell_deadlift',
    slug: 'barbell_deadlift',
    name: 'Peso Muerto Convencional',
    description:
        'Levantamiento desde el suelo. Mejora fuerza general de cadena posterior y agarre, útil en fases de base.',
    videoUrl: '',
    levelId: LevelId.advanced,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.hinge,
    muscleGroupIds: [MuscleGroupId.glutes, MuscleGroupId.hamstrings, MuscleGroupId.erectors],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.jump],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.offSeason, TrainingPhaseId.preSeason],
    equipmentIds: [EquipmentId.barra, EquipmentId.discos],
    contraindicationIds: [ContraindicationId.lumbar],
  ),

  Exercise(
    id: 'ex_hip_thrust_barbell',
    slug: 'hip_thrust_barbell',
    name: 'Hip Thrust con Barra',
    description:
        'Elevación de cadera apoyando la espalda en banco. Muy útil para hipertrofia de glúteos y fuerza de extensión.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.hinge,
    muscleGroupIds: [MuscleGroupId.glutes, MuscleGroupId.hamstrings, MuscleGroupId.core],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.jump],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.barra, EquipmentId.discos, EquipmentId.banco],
    contraindicationIds: [ContraindicationId.lumbar],
  ),

  Exercise(
    id: 'ex_leg_press',
    slug: 'leg_press_machine',
    name: 'Prensa de Piernas',
    description:
        'Ejercicio guiado para cuádriceps y glúteos. Útil para hipertrofia y cuando no se puede cargar tanto la columna.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.glutes, MuscleGroupId.hamstrings],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.jump],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.banco],
    contraindicationIds: [ContraindicationId.rodilla],
  ),

  Exercise(
    id: 'ex_stepup_db',
    slug: 'step_up_dumbbells',
    name: 'Step-Up al Banco con Mancuernas',
    description:
        'Subir al banco de forma unilateral. Trabaja cuádriceps, glúteos y estabilidad de rodilla y tobillo.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.lunge,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.glutes, MuscleGroupId.core],
    qualityIds: [QualityId.strength, QualityId.stability],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.approach, VolleyballTransferId.jump],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.mancuernas, EquipmentId.banco],
    contraindicationIds: [ContraindicationId.rodilla],
  ),

  Exercise(
    id: 'ex_calf_raise_standing',
    slug: 'standing_calf_raise',
    name: 'Elevación de Talones de Pie',
    description:
        'Trabajo de gemelos y sóleo de pie. Puede hacerse con peso corporal o con carga extra.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.calves],
    qualityIds: [QualityId.strength, QualityId.stability],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.jump, VolleyballTransferId.landing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.tobillo],
  ),

  Exercise(
    id: 'ex_glute_bridge_bw',
    slug: 'glute_bridge_bw',
    name: 'Glute Bridge con Peso Corporal',
    description:
        'Puente de glúteos desde el suelo. Ideal para aprender activación de glúteos y proteger la zona lumbar.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.prevencion,
    movementPatternId: MovementPatternId.hinge,
    muscleGroupIds: [MuscleGroupId.glutes, MuscleGroupId.hamstrings],
    qualityIds: [QualityId.stability],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.jump],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.colchoneta],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'ex_single_leg_rdl_db',
    slug: 'single_leg_rdl_db',
    name: 'Peso Muerto Rumano Unilateral con Mancuerna',
    description:
        'Bisagra unilateral con foco en estabilidad de cadera, isquiosurales y glúteos.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.hinge,
    muscleGroupIds: [MuscleGroupId.hamstrings, MuscleGroupId.glutes, MuscleGroupId.core],
    qualityIds: [QualityId.strength, QualityId.stability],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.jump, VolleyballTransferId.landing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.mancuernas],
    contraindicationIds: [ContraindicationId.rodilla],
  ),

  // =========================
  // 2) EMPUJE - PECHO / HOMBRO / TRÍCEPS
  // =========================

  Exercise(
    id: 'ex_bench_press_barbell',
    slug: 'bench_press_barbell',
    name: 'Press Banca con Barra',
    description:
        'Ejercicio básico de fuerza para pecho, hombros y tríceps. Útil en fases de base y fuerza máxima.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.push,
    muscleGroupIds: [MuscleGroupId.delts, MuscleGroupId.lats, MuscleGroupId.core],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.offSeason, TrainingPhaseId.preSeason],
    equipmentIds: [EquipmentId.barra, EquipmentId.discos, EquipmentId.banco],
    contraindicationIds: [ContraindicationId.hombro],
  ),

  Exercise(
    id: 'ex_incline_db_press',
    slug: 'incline_db_press',
    name: 'Press Inclinado con Mancuernas',
    description:
        'Variante inclinada para enfatizar la porción superior del pecho y deltoides anteriores.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.push,
    muscleGroupIds: [MuscleGroupId.delts, MuscleGroupId.lats],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.mancuernas, EquipmentId.banco],
    contraindicationIds: [ContraindicationId.hombro],
  ),

  Exercise(
    id: 'ex_pushup',
    slug: 'pushup_standard',
    name: 'Flexiones de Brazos (Push-Up)',
    description:
        'Ejercicio de calistenia clásico. Trabaja pecho, hombros, tríceps y core, muy transferible al vóley.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.push,
    muscleGroupIds: [MuscleGroupId.delts, MuscleGroupId.core],
    qualityIds: [QualityId.strength, QualityId.stability],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.hombro],
  ),

  Exercise(
    id: 'ex_dips_parallel',
    slug: 'dips_parallel_bars',
    name: 'Fondos en Paralelas',
    description:
        'Ejercicio de empuje pesado con propio peso. Enfatiza tríceps, pecho y hombros.',
    videoUrl: '',
    levelId: LevelId.advanced,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.push,
    muscleGroupIds: [MuscleGroupId.delts, MuscleGroupId.core],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.offSeason, TrainingPhaseId.preSeason],
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.hombro],
  ),

  Exercise(
    id: 'ex_oh_press_barbell',
    slug: 'overhead_press_barbell',
    name: 'Press Militar con Barra',
    description:
        'Press vertical por encima de la cabeza. Mejora fuerza de hombros, trapecios y core en posición de bloqueo.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.push,
    muscleGroupIds: [MuscleGroupId.delts, MuscleGroupId.core],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.block, VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.barra, EquipmentId.discos],
    contraindicationIds: [ContraindicationId.hombro, ContraindicationId.lumbar],
  ),

  Exercise(
    id: 'ex_arnold_press_db',
    slug: 'arnold_press_db',
    name: 'Press Arnold con Mancuernas',
    description:
        'Variante de hombro con rotación, trabajando porciones anterior y lateral del deltoides.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.push,
    muscleGroupIds: [MuscleGroupId.delts],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.mancuernas],
    contraindicationIds: [ContraindicationId.hombro],
  ),

  Exercise(
    id: 'ex_lateral_raise_db',
    slug: 'lateral_raise_db',
    name: 'Elevaciones Laterales con Mancuernas',
    description:
        'Aislación de deltoides medios, ideal como accesorio para hipertrofia de hombro.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.push,
    muscleGroupIds: [MuscleGroupId.delts],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.mancuernas],
    contraindicationIds: [ContraindicationId.hombro],
  ),

  Exercise(
    id: 'ex_pike_pushup',
    slug: 'pike_pushup_bw',
    name: 'Pike Push-Up',
    description:
        'Flexión en posición pike, simula el patrón de press vertical usando solo peso corporal.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.push,
    muscleGroupIds: [MuscleGroupId.delts, MuscleGroupId.core],
    qualityIds: [QualityId.strength, QualityId.stability],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.block],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.hombro],
  ),

  // =========================
  // 3) TIRÓN - ESPALDA / BÍCEPS
  // =========================

  Exercise(
    id: 'ex_pullup_pronated',
    slug: 'pullup_pronated',
    name: 'Dominadas Pronas',
    description:
        'Dominadas con agarre prono. Base de fuerza para espalda y agarre, muy transferible a gestos explosivos.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.pull,
    muscleGroupIds: [MuscleGroupId.lats, MuscleGroupId.delts, MuscleGroupId.core],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.hombro],
  ),

  Exercise(
    id: 'ex_chinup_supinated',
    slug: 'chinup_supinated',
    name: 'Chin-Up Supino',
    description:
        'Dominada con agarre supino. Mayor participación de bíceps, trabajo completo de tren superior.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.pull,
    muscleGroupIds: [MuscleGroupId.lats, MuscleGroupId.delts],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.hombro],
  ),

  Exercise(
    id: 'ex_bentover_row_bb',
    slug: 'bentover_row_barbell',
    name: 'Remo Inclinado con Barra',
    description:
        'Remo de pie con el tronco inclinado. Trabaja espalda media, baja y core en isometría.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.pull,
    muscleGroupIds: [MuscleGroupId.lats, MuscleGroupId.erectors, MuscleGroupId.core],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.offSeason, TrainingPhaseId.preSeason],
    equipmentIds: [EquipmentId.barra, EquipmentId.discos],
    contraindicationIds: [ContraindicationId.lumbar],
  ),

  Exercise(
    id: 'ex_one_arm_row_db',
    slug: 'one_arm_row_db',
    name: 'Remo a Una Mano con Mancuerna',
    description:
        'Remo unilateral apoyando una mano en banco. Permite mayor rango y enfoque en la dorsales.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.pull,
    muscleGroupIds: [MuscleGroupId.lats, MuscleGroupId.delts],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.mancuernas, EquipmentId.banco],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'ex_cable_row_seated',
    slug: 'seated_cable_row',
    name: 'Remo en Polea Sentado',
    description:
        'Remo guiado con cable. Permite trabajo controlado de espalda media con menos demanda de zona lumbar.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.pull,
    muscleGroupIds: [MuscleGroupId.lats, MuscleGroupId.delts],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'ex_face_pull',
    slug: 'face_pull_cable',
    name: 'Face Pull en Polea',
    description:
        'Remo alto hacia la cara. Excelente para manguito rotador y parte posterior del hombro.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.prevencion,
    movementPatternId: MovementPatternId.pull,
    muscleGroupIds: [MuscleGroupId.rotatorCuff, MuscleGroupId.delts],
    qualityIds: [QualityId.stability, QualityId.mobility],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.banda],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'ex_inverted_row_trx',
    slug: 'inverted_row_trx',
    name: 'Remo Invertido en TRX',
    description:
        'Remo con el cuerpo suspendido. Variante de calistenia para espalda, hombros y core.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.fuerza,
    movementPatternId: MovementPatternId.pull,
    muscleGroupIds: [MuscleGroupId.lats, MuscleGroupId.delts, MuscleGroupId.core],
    qualityIds: [QualityId.strength, QualityId.stability],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.trx],
    contraindicationIds: [],
  ),

  // =========================
  // 4) CORE / ESTABILIDAD
  // =========================

  Exercise(
    id: 'ex_plank',
    slug: 'plank_hold',
    name: 'Plancha Frontal',
    description:
        'Isometría de core en posición de plancha. Trabaja estabilización anti-extensión de columna.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.core,
    movementPatternId: MovementPatternId.antiRotation,
    muscleGroupIds: [MuscleGroupId.core],
    qualityIds: [QualityId.stability, QualityId.endurance],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.landing, VolleyballTransferId.defenseShuffle],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.colchoneta],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'ex_side_plank',
    slug: 'side_plank_hold',
    name: 'Plancha Lateral',
    description:
        'Variante lateral. Trabaja oblicuos y estabilidad frontal y lateral de cadera y tronco.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.core,
    movementPatternId: MovementPatternId.antiRotation,
    muscleGroupIds: [MuscleGroupId.core],
    qualityIds: [QualityId.stability],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.landing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.colchoneta],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'ex_dead_bug',
    slug: 'dead_bug_core',
    name: 'Dead Bug',
    description:
        'Ejercicio de control lumbo-pélvico alternando brazos y piernas. Muy usado en prevención.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.prevencion,
    movementPatternId: MovementPatternId.antiRotation,
    muscleGroupIds: [MuscleGroupId.core],
    qualityIds: [QualityId.stability],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.landing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.colchoneta],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'ex_pallof_press',
    slug: 'pallof_press_band',
    name: 'Pallof Press con Banda',
    description:
        'Anti-rotación de tronco contra resistencia lateral. Clave para estabilidad de core en deportistas.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.core,
    movementPatternId: MovementPatternId.antiRotation,
    muscleGroupIds: [MuscleGroupId.core],
    qualityIds: [QualityId.stability],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.defenseShuffle, VolleyballTransferId.landing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.banda],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'ex_hanging_knee_raise',
    slug: 'hanging_knee_raise',
    name: 'Elevación de Rodillas Colgado',
    description:
        'Ejercicio de core en barra, enfatiza flexores de cadera y abdominales inferiores.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.core,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.core],
    qualityIds: [QualityId.strength],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.hombro],
  ),

  // =========================
  // 5) POTENCIA / PLIOMETRÍA
  // =========================

  Exercise(
    id: 'ex_box_jump',
    slug: 'box_jump_caja_alta',
    name: 'Box Jump a Caja',
    description:
        'Salto explosivo a caja. Potencia de extensión de cadera y rodilla con menor impacto en la caída.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.pliometria,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.glutes, MuscleGroupId.hamstrings, MuscleGroupId.calves],
    qualityIds: [QualityId.power],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.jump, VolleyballTransferId.landing, VolleyballTransferId.block],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.preSeason, TrainingPhaseId.inSeason],
    equipmentIds: [EquipmentId.caja],
    contraindicationIds: [ContraindicationId.rodilla, ContraindicationId.impactoAlto],
  ),

  Exercise(
    id: 'ex_broad_jump',
    slug: 'broad_jump',
    name: 'Salto Horizontal (Broad Jump)',
    description:
        'Salto a máxima distancia hacia adelante. Enfocado en potencia de cadera y proyección.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.pliometria,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.glutes, MuscleGroupId.hamstrings, MuscleGroupId.quads],
    qualityIds: [QualityId.power, QualityId.speed],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.approach, VolleyballTransferId.jump],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.preSeason],
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.rodilla, ContraindicationId.tobillo, ContraindicationId.impactoAlto],
  ),

  Exercise(
    id: 'ex_lateral_skater_jump',
    slug: 'lateral_skater_jump',
    name: 'Skater Jump Lateral',
    description:
        'Saltos laterales a una pierna. Trabaja potencia, estabilidad y control en plano frontal.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.pliometria,
    movementPatternId: MovementPatternId.lunge,
    muscleGroupIds: [MuscleGroupId.glutes, MuscleGroupId.quads, MuscleGroupId.core],
    qualityIds: [QualityId.power, QualityId.agility],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.defenseShuffle],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.preSeason, TrainingPhaseId.inSeason],
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.rodilla, ContraindicationId.tobillo, ContraindicationId.impactoAlto],
  ),

  Exercise(
    id: 'ex_split_squat_jump',
    slug: 'split_squat_jump',
    name: 'Saltos de Split Squat',
    description:
        'Saltos alternando piernas en posición de lunge. Alta demanda de potencia y estabilidad de rodilla.',
    videoUrl: '',
    levelId: LevelId.advanced,
    categoryId: CategoryId.pliometria,
    movementPatternId: MovementPatternId.lunge,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.glutes, MuscleGroupId.hamstrings],
    qualityIds: [QualityId.power, QualityId.agility],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.approach, VolleyballTransferId.jump],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.preSeason],
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.rodilla, ContraindicationId.impactoAlto],
  ),

  Exercise(
    id: 'ex_countermovement_jump',
    slug: 'cmj_bodyweight',
    name: 'Countermovement Jump (CMJ)',
    description:
        'Salto vertical con contramovimiento. Test y ejercicio clásico de potencia para vóley.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.potencia,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.glutes, MuscleGroupId.hamstrings, MuscleGroupId.calves],
    qualityIds: [QualityId.power],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.jump, VolleyballTransferId.block],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.impactoAlto, ContraindicationId.rodilla],
  ),

  // =========================
  // 6) ACONDICIONAMIENTO / POWER-CON
  // =========================

  Exercise(
    id: 'ex_kb_swing',
    slug: 'kettlebell_swing',
    name: 'Kettlebell Swing',
    description:
        'Bisagra explosiva de cadera con kettlebell. Combina potencia y acondicionamiento.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.acondicionamiento,
    movementPatternId: MovementPatternId.hinge,
    muscleGroupIds: [MuscleGroupId.glutes, MuscleGroupId.hamstrings, MuscleGroupId.erectors, MuscleGroupId.core],
    qualityIds: [QualityId.power, QualityId.endurance],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.jump],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.kettlebell],
    contraindicationIds: [ContraindicationId.lumbar, ContraindicationId.cardio],
  ),

  Exercise(
    id: 'ex_battle_ropes',
    slug: 'battle_ropes_waves',
    name: 'Battle Ropes (Olas)',
    description:
        'Olas con cuerdas de batalla. Alta demanda de acondicionamiento de tren superior y core.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.acondicionamiento,
    movementPatternId: MovementPatternId.rotation,
    muscleGroupIds: [MuscleGroupId.delts, MuscleGroupId.core],
    qualityIds: [QualityId.endurance, QualityId.power],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.sogaBatalla],
    contraindicationIds: [ContraindicationId.cardio, ContraindicationId.hombro],
  ),

  Exercise(
    id: 'ex_sled_push',
    slug: 'sled_push',
    name: 'Empuje de Trineo',
    description:
        'Empuje pesado de trineo. Mejora fuerza de pierna y acondicionamiento específico.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.acondicionamiento,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.glutes, MuscleGroupId.hamstrings, MuscleGroupId.core],
    qualityIds: [QualityId.strength, QualityId.endurance],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.approach],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.preSeason, TrainingPhaseId.offSeason],
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.cardio, ContraindicationId.rodilla],
  ),

  Exercise(
    id: 'ex_burpee',
    slug: 'burpee_bw',
    name: 'Burpee',
    description:
        'Ejercicio de cuerpo completo con salto. Alta demanda de acondicionamiento y potencia general.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.acondicionamiento,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.core, MuscleGroupId.quads, MuscleGroupId.glutes],
    qualityIds: [QualityId.endurance, QualityId.power],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.jump],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.cardio, ContraindicationId.impactoAlto],
  ),

  // =========================
  // 7) PREVENCIÓN / REHAB GIMNASIO
  // =========================

  Exercise(
    id: 'ex_band_external_rotation',
    slug: 'band_external_rotation',
    name: 'Rotación Externa de Hombro con Banda',
    description:
        'Ejercicio de manguito rotador para fortalecer rotadores externos del hombro.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.prevencion,
    movementPatternId: MovementPatternId.rotation,
    muscleGroupIds: [MuscleGroupId.rotatorCuff],
    qualityIds: [QualityId.stability, QualityId.mobility],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.banda],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'ex_spanish_squat',
    slug: 'spanish_squat_band',
    name: 'Spanish Squat con Banda',
    description:
        'Sentadilla sostenida con banda detrás de las rodillas. Enfocada en cuádriceps, usada en rehab de rodilla.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.prevencion,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.quads],
    qualityIds: [QualityId.stability, QualityId.strength],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.banda],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'ex_nordic_hamstring',
    slug: 'nordic_hamstring_curl',
    name: 'Nordic Hamstring Curl',
    description:
        'Ejercicio excéntrico de isquiosurales. Muy usado en prevención de lesiones de muslo posterior.',
    videoUrl: '',
    levelId: LevelId.advanced,
    categoryId: CategoryId.prevencion,
    movementPatternId: MovementPatternId.hinge,
    muscleGroupIds: [MuscleGroupId.hamstrings],
    qualityIds: [QualityId.strength, QualityId.stability],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.banco, EquipmentId.colchoneta],
    contraindicationIds: [ContraindicationId.rodilla],
  ),

  Exercise(
    id: 'ex_copenhagen_plank',
    slug: 'copenhagen_plank',
    name: 'Plancha Copenhague',
    description:
        'Isometría lateral apoyando la pierna en banco. Trabaja aductores y core, utilizado en prevención de cadera.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.prevencion,
    movementPatternId: MovementPatternId.antiRotation,
    muscleGroupIds: [MuscleGroupId.core, MuscleGroupId.glutes],
    qualityIds: [QualityId.stability],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.banco, EquipmentId.colchoneta],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'ex_ytw_raise',
    slug: 'ytw_raise_db',
    name: 'Elevaciones Y-T-W',
    description:
        'Ejercicio de hombro en patrones Y, T y W. Enfocado en musculatura escapular y deltoides posteriores.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.prevencion,
    movementPatternId: MovementPatternId.pull,
    muscleGroupIds: [MuscleGroupId.rotatorCuff, MuscleGroupId.delts],
    qualityIds: [QualityId.stability, QualityId.mobility],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.mancuernas, EquipmentId.colchoneta],
    contraindicationIds: [],
  ),

];

/// 🚀 FUNCIÓN PARA SEEDear EN FIRESTORE
///
/// Colección sugerida: "exercises"
/// - Usa el campo `id` como documentId.
/// - `merge: true` para no pisar campos extra si vuelves a correrlo.
Future<void> seedGymExercises() async {
  final firestore = FirebaseFirestore.instance;
  final collection = firestore.collection('exercises');

  for (final ex in gymExercises) {
    await collection.doc(ex.id).set(ex.toJson(), SetOptions(merge: true));
  }
}
