// lib/seeders/mobility_warmup_cooldown_seeder.dart

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:voley_app/src/catalogos/enums.dart';
import 'package:voley_app/src/models/bd/exercise.dart';

/// 🟠 + 🔵 Ejercicios de MOVILIDAD / CALENTAMIENTO y ENFRIAMIENTO
///
/// - Movilidad/calentamiento → CategoryId.movilidad o CategoryId.acondicionamiento
/// - Enfriamiento → CategoryId.movilidad (mayoría estiramientos suaves)

final List<Exercise> mobilityWarmupCooldownExercises = [

  // ================================================================
  // 🟠 SECCIÓN: MOVILIDAD / CALENTAMIENTO DINÁMICO
  // ================================================================

  Exercise(
    id: 'mob_jumping_jacks_0',
    slug: 'jumping_jacks',
    name: 'Jumping Jacks',
    description:
        'Salto abierto y cerrado con brazos arriba. Eleva la temperatura corporal y activa todo el cuerpo.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.acondicionamiento,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.calves, MuscleGroupId.core],
    qualityIds: [QualityId.endurance, QualityId.speed],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.jump, VolleyballTransferId.defenseShuffle],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.impactoAlto, ContraindicationId.cardio],
  ),

  Exercise(
    id: 'mob_high_knees_1',
    slug: 'high_knees_running',
    name: 'High Knees en el Lugar',
    description:
        'Correr en el lugar elevando rodillas a la altura de la cadera. Excelente para calentar cadera y activar core.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.acondicionamiento,
    movementPatternId: MovementPatternId.lunge,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.glutes, MuscleGroupId.core],
    qualityIds: [QualityId.speed, QualityId.agility, QualityId.endurance],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.defenseShuffle, VolleyballTransferId.approach],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.cardio, ContraindicationId.rodilla],
  ),

  Exercise(
    id: 'mob_butt_kicks_2',
    slug: 'butt_kicks',
    name: 'Butt Kicks',
    description:
        'Correr en el lugar llevando talones hacia los glúteos. Calienta isquios y favorece la circulación.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.acondicionamiento,
    movementPatternId: MovementPatternId.lunge,
    muscleGroupIds: [MuscleGroupId.hamstrings, MuscleGroupId.calves],
    qualityIds: [QualityId.speed, QualityId.endurance],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.approach],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.cardio],
  ),

  Exercise(
    id: 'mob_carioca_shuffles_3',
    slug: 'carioca_shuffles',
    name: 'Carioca / Cruce Lateral',
    description:
        'Desplazamiento lateral cruzando las piernas por delante y por detrás. Mejora coordinación y movilidad de cadera.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.acondicionamiento,
    movementPatternId: MovementPatternId.lunge,
    muscleGroupIds: [MuscleGroupId.glutes, MuscleGroupId.hamstrings, MuscleGroupId.core],
    qualityIds: [QualityId.agility, QualityId.speed],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.defenseShuffle],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.rodilla, ContraindicationId.tobillo],
  ),

  Exercise(
    id: 'mob_arm_circles_4',
    slug: 'arm_circles',
    name: 'Círculos de Brazos',
    description:
        'Círculos amplios hacia adelante y hacia atrás con ambos brazos. Calienta hombros y cintura escapular.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.rotation,
    muscleGroupIds: [MuscleGroupId.delts, MuscleGroupId.rotatorCuff],
    qualityIds: [QualityId.mobility],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing, VolleyballTransferId.block],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.hombro],
  ),

  Exercise(
    id: 'mob_band_dislocates_5',
    slug: 'band_dislocates',
    name: 'Dislocaciones de Hombro con Banda',
    description:
        'Pasar una banda o palo desde frente del cuerpo por encima de la cabeza hasta la espalda, manteniendo codos extendidos.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.rotation,
    muscleGroupIds: [MuscleGroupId.delts, MuscleGroupId.rotatorCuff],
    qualityIds: [QualityId.mobility, QualityId.stability],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.preSeason],
    equipmentIds: [EquipmentId.banda],
    contraindicationIds: [ContraindicationId.hombro],
  ),

  Exercise(
    id: 'mob_leg_swings_front_back_6',
    slug: 'leg_swings_front_back',
    name: 'Balanceo de Pierna Frontal',
    description:
        'De pie, balancear una pierna hacia adelante y hacia atrás de forma controlada. Movilidad dinámica de cadera e isquios.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.hinge,
    muscleGroupIds: [MuscleGroupId.hamstrings, MuscleGroupId.glutes],
    qualityIds: [QualityId.mobility],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.approach, VolleyballTransferId.landing],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.rodilla, ContraindicationId.tobillo],
  ),

  Exercise(
    id: 'mob_leg_swings_side_7',
    slug: 'leg_swings_side',
    name: 'Balanceo de Pierna Lateral',
    description:
        'Balancear una pierna de lado a lado cruzando delante del cuerpo. Trabaja aductores y abductores dinámicamente.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.lunge,
    muscleGroupIds: [MuscleGroupId.glutes, MuscleGroupId.hamstrings],
    qualityIds: [QualityId.mobility],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.defenseShuffle],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.tobillo],
  ),

  Exercise(
    id: 'mob_worlds_greatest_dynamic_8',
    slug: 'worlds_greatest_stretch_dynamic',
    name: 'World’s Greatest Stretch (Dinámico)',
    description:
        'Zancada profunda, mano dentro del pie, rotación de columna y cambio de lado. Movilidad global antes de entrenar.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.lunge,
    muscleGroupIds: [MuscleGroupId.glutes, MuscleGroupId.hamstrings, MuscleGroupId.core],
    qualityIds: [QualityId.mobility, QualityId.stability],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.approach, VolleyballTransferId.landing],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.preSeason],
    equipmentIds: [EquipmentId.colchoneta],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'mob_inch_worm_9',
    slug: 'inch_worm_walkout',
    name: 'Inch Worm (Walkout)',
    description:
        'Desde de pie, caminar con las manos hacia posición de plancha y volver. Calienta hombros, core y posterior de pierna.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.hinge,
    muscleGroupIds: [MuscleGroupId.hamstrings, MuscleGroupId.core, MuscleGroupId.delts],
    qualityIds: [QualityId.mobility, QualityId.endurance],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.landing],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.preSeason],
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.lumbar, ContraindicationId.cardio],
  ),

  Exercise(
    id: 'mob_squat_to_stand_10',
    slug: 'deep_squat_to_stand',
    name: 'Deep Squat to Stand',
    description:
        'Tomar la punta de los pies, bajar a sentadilla profunda y volver a extender rodillas. Muy usado en calentamiento de cadera y tobillo.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.glutes, MuscleGroupId.calves],
    qualityIds: [QualityId.mobility, QualityId.stability],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.landing, VolleyballTransferId.jump],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.rodilla],
  ),

  Exercise(
    id: 'mob_cat_camel_dynamic_11',
    slug: 'cat_camel_dynamic',
    name: 'Cat-Camel Dinámico',
    description:
        'Alternar arqueo y redondeo de la columna en cuadrupedia. Calentamiento suave de columna antes de cargas.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.rotation,
    muscleGroupIds: [MuscleGroupId.erectors, MuscleGroupId.core],
    qualityIds: [QualityId.mobility],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.colchoneta],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'mob_thoracic_rotation_quad_12',
    slug: 'thoracic_rotation_quadruped_mob',
    name: 'Rotación Torácica en Cuadrupedia (Calentamiento)',
    description:
        'En cuadrupedia, mano en la nuca y abrir codo hacia el techo, luego cambiar de lado. Mejora rotación torácica previa al juego.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.rotation,
    muscleGroupIds: [MuscleGroupId.core, MuscleGroupId.erectors],
    qualityIds: [QualityId.mobility],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.armSwing, VolleyballTransferId.block],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [EquipmentId.colchoneta],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'mob_ankle_dorsiflexion_dynamic_13',
    slug: 'ankle_dorsiflexion_pulse',
    name: 'Movilidad de Tobillo con Pulsos',
    description:
        'Apoyar el pie adelantado y llevar rodilla hacia adelante con pequeños rebotes controlados. Ideal antes de saltar.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.calves],
    qualityIds: [QualityId.mobility],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [VolleyballTransferId.landing, VolleyballTransferId.jump],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [],
  ),

  // ================================================================
  // 🔵 SECCIÓN: ENFRIAMIENTO / VUELTA A LA CALMA
  // ================================================================

  Exercise(
    id: 'cool_hamstring_band_stretch_14',
    slug: 'supine_hamstring_band_stretch',
    name: 'Estiramiento de Isquios con Banda (Supino)',
    description:
        'Tumbado boca arriba, elevar una pierna y traccionar suavemente con banda. Mantener de 20–30 segundos.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.hinge,
    muscleGroupIds: [MuscleGroupId.hamstrings],
    qualityIds: [QualityId.mobility],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.taper],
    equipmentIds: [EquipmentId.banda, EquipmentId.colchoneta],
    contraindicationIds: [ContraindicationId.lumbar],
  ),

  Exercise(
    id: 'cool_hip_flexor_half_kneeling_15',
    slug: 'hip_flexor_half_kneeling_stretch',
    name: 'Estiramiento de Flexores de Cadera en Zancada',
    description:
        'En posición de media zancada, inclinar la pelvis hacia adelante para sentir el estiramiento en la cadera atrasada.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.lunge,
    muscleGroupIds: [MuscleGroupId.quads, MuscleGroupId.glutes],
    qualityIds: [QualityId.mobility],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.taper],
    equipmentIds: [EquipmentId.colchoneta],
    contraindicationIds: [ContraindicationId.rodilla],
  ),

  Exercise(
    id: 'cool_pigeon_glute_stretch_16',
    slug: 'pigeon_pose_glute_stretch',
    name: 'Pigeon Pose / Estiramiento de Glúteo',
    description:
        'Desde posición de plancha, adelantar una pierna flexionada y apoyar la cadera. Estira glúteos y rotadores de cadera.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.rotation,
    muscleGroupIds: [MuscleGroupId.glutes, MuscleGroupId.core],
    qualityIds: [QualityId.mobility],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.offSeason],
    equipmentIds: [EquipmentId.colchoneta],
    contraindicationIds: [ContraindicationId.rodilla],
  ),

  Exercise(
    id: 'cool_calf_wall_stretch_17',
    slug: 'calf_wall_stretch',
    name: 'Estiramiento de Gemelo en Pared',
    description:
        'Apoyar manos en pared, pierna atrás con talón en el suelo y rodilla extendida. Mantener 20–30 segundos.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.squat,
    muscleGroupIds: [MuscleGroupId.calves],
    qualityIds: [QualityId.mobility],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: TrainingPhaseId.values,
    equipmentIds: [],
    contraindicationIds: [],
  ),

  Exercise(
    id: 'cool_adductor_side_lunge_hold_18',
    slug: 'adductor_side_lunge_hold',
    name: 'Estiramiento de Aductores en Zancada Lateral',
    description:
        'Con piernas abiertas, flexionar una rodilla y mantener la otra extendida. Sentir estiramiento en la cara interna del muslo.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.lunge,
    muscleGroupIds: [MuscleGroupId.glutes, MuscleGroupId.hamstrings],
    qualityIds: [QualityId.mobility],
    planeId: PlaneId.frontal,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.taper],
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.rodilla],
  ),

  Exercise(
    id: 'cool_chest_doorway_stretch_19',
    slug: 'chest_doorway_stretch',
    name: 'Estiramiento de Pecho en Marco de Puerta',
    description:
        'Antebrazos apoyados en el marco de la puerta, avanzar el pecho suavemente para estirar pectorales.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.push,
    muscleGroupIds: [MuscleGroupId.delts],
    qualityIds: [QualityId.mobility],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [VolleyballTransferId.armSwing, VolleyballTransferId.block],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.offSeason],
    equipmentIds: [],
    contraindicationIds: [ContraindicationId.hombro],
  ),

  Exercise(
    id: 'cool_sleeper_stretch_20',
    slug: 'sleeper_stretch',
    name: 'Sleeper Stretch (Rotación Interna de Hombro)',
    description:
        'Acostado de lado, hombro y codo a 90°. Con la otra mano empujar suavemente el antebrazo hacia el suelo.',
    videoUrl: '',
    levelId: LevelId.intermediate,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.rotation,
    muscleGroupIds: [MuscleGroupId.rotatorCuff],
    qualityIds: [QualityId.mobility],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.unilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.offSeason],
    equipmentIds: [EquipmentId.colchoneta],
    contraindicationIds: [ContraindicationId.hombro],
  ),

  Exercise(
    id: 'cool_child_pose_21',
    slug: 'child_pose',
    name: 'Child’s Pose',
    description:
        'Desde cuatro apoyos, sentarse sobre talones y extender brazos hacia adelante. Relaja columna y hombros.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.hinge,
    muscleGroupIds: [MuscleGroupId.erectors, MuscleGroupId.core],
    qualityIds: [QualityId.mobility, QualityId.endurance],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.taper],
    equipmentIds: [EquipmentId.colchoneta],
    contraindicationIds: [ContraindicationId.lumbar],
  ),

  Exercise(
    id: 'cool_spinal_twist_supine_22',
    slug: 'supine_spinal_twist',
    name: 'Rotación Lumbar en Supino',
    description:
        'Tumbado boca arriba, llevar rodillas flexionadas hacia un lado manteniendo hombros en el suelo.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.movilidad,
    movementPatternId: MovementPatternId.rotation,
    muscleGroupIds: [MuscleGroupId.core, MuscleGroupId.erectors],
    qualityIds: [QualityId.mobility],
    planeId: PlaneId.transverse,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.offSeason],
    equipmentIds: [EquipmentId.colchoneta],
    contraindicationIds: [ContraindicationId.lumbar],
  ),

  Exercise(
    id: 'cool_breathing_crook_lying_23',
    slug: 'breathing_crook_lying',
    name: 'Respiración Diafragmática en Crook Lying',
    description:
        'Tumbado boca arriba con rodillas flexionadas, respirar profundo hacia el abdomen, exhalando lento por la boca.',
    videoUrl: '',
    levelId: LevelId.beginner,
    categoryId: CategoryId.acondicionamiento,
    movementPatternId: MovementPatternId.antiRotation,
    muscleGroupIds: [MuscleGroupId.core],
    qualityIds: [QualityId.endurance, QualityId.stability],
    planeId: PlaneId.sagittal,
    dominanceId: DominanceId.bilateral,
    vbTransferIds: [],
    positions: VolleyballPositionId.values,
    phases: [TrainingPhaseId.taper],
    equipmentIds: [EquipmentId.colchoneta],
    contraindicationIds: [],
  ),

];

/// 🚀 Seed de ejercicios de MOVILIDAD/CALENTAMIENTO y ENFRIAMIENTO en Firestore
///
/// Colección sugerida: "exercises"
Future<void> seedMobilityWarmupCooldownExercises() async {
  final firestore = FirebaseFirestore.instance;
  final collection = firestore.collection('exercises');

  for (final ex in mobilityWarmupCooldownExercises) {
    await collection.doc(ex.id).set(ex.toJson(), SetOptions(merge: true));
  }
}
